export interface Emoji {
  emoji: string;
  unified: string;
  name: string;
}

export const EMOJI_CATEGORIES = {
  smileys: [
    { emoji: '😀', unified: '1f600', name: 'grinning face' },
    { emoji: '😃', unified: '1f603', name: 'grinning face with big eyes' },
    { emoji: '😄', unified: '1f604', name: 'grinning face with smiling eyes' },
    { emoji: '😁', unified: '1f601', name: 'beaming face with smiling eyes' },
    { emoji: '😆', unified: '1f606', name: 'grinning squinting face' },
    { emoji: '😅', unified: '1f605', name: 'grinning face with sweat' },
    { emoji: '🤣', unified: '1f923', name: 'rolling on the floor laughing' },
    { emoji: '😂', unified: '1f602', name: 'face with tears of joy' },
    { emoji: '🙂', unified: '1f642', name: 'slightly smiling face' },
    { emoji: '🙃', unified: '1f643', name: 'upside-down face' },
    { emoji: '😉', unified: '1f609', name: 'winking face' },
    { emoji: '😊', unified: '1f60a', name: 'smiling face with smiling eyes' },
    { emoji: '😇', unified: '1f607', name: 'smiling face with halo' },
    { emoji: '🥰', unified: '1f970', name: 'smiling face with hearts' },
    { emoji: '😍', unified: '1f60d', name: 'smiling face with heart-eyes' },
    { emoji: '🤩', unified: '1f929', name: 'star-struck' },
    { emoji: '😘', unified: '1f618', name: 'face blowing a kiss' },
    { emoji: '😗', unified: '1f617', name: 'kissing face' },
    { emoji: '😚', unified: '1f61a', name: 'kissing face with closed eyes' },
    { emoji: '😙', unified: '1f619', name: 'kissing face with smiling eyes' },
    { emoji: '😋', unified: '1f60b', name: 'face savoring food' },
    { emoji: '😛', unified: '1f61b', name: 'face with tongue' },
    { emoji: '😜', unified: '1f61c', name: 'winking face with tongue' },
    { emoji: '🤪', unified: '1f92a', name: 'zany face' },
    { emoji: '😝', unified: '1f61d', name: 'squinting face with tongue' },
    { emoji: '🤑', unified: '1f911', name: 'money-mouth face' },
    { emoji: '🤗', unified: '1f917', name: 'hugging face' },
    { emoji: '🤭', unified: '1f92d', name: 'face with hand over mouth' },
    { emoji: '🤫', unified: '1f92b', name: 'shushing face' },
    { emoji: '🤔', unified: '1f914', name: 'thinking face' },
    { emoji: '🤐', unified: '1f910', name: 'zipper-mouth face' },
    { emoji: '🤨', unified: '1f928', name: 'face with raised eyebrow' },
    { emoji: '😐', unified: '1f610', name: 'neutral face' },
    { emoji: '😑', unified: '1f611', name: 'expressionless face' },
    { emoji: '😶', unified: '1f636', name: 'face without mouth' },
    { emoji: '😏', unified: '1f60f', name: 'smirking face' },
    { emoji: '😒', unified: '1f612', name: 'unamused face' },
    { emoji: '🙄', unified: '1f644', name: 'face with rolling eyes' },
    { emoji: '😬', unified: '1f62c', name: 'grimacing face' },
    { emoji: '🤥', unified: '1f925', name: 'lying face' },
    { emoji: '😌', unified: '1f60c', name: 'relieved face' },
    { emoji: '😔', unified: '1f614', name: 'pensive face' },
    { emoji: '😪', unified: '1f62a', name: 'sleepy face' },
    { emoji: '🤤', unified: '1f924', name: 'drooling face' },
    { emoji: '😴', unified: '1f634', name: 'sleeping face' },
    { emoji: '😷', unified: '1f637', name: 'face with medical mask' },
    { emoji: '🤒', unified: '1f912', name: 'face with thermometer' },
    { emoji: '🤕', unified: '1f915', name: 'face with head-bandage' },
    { emoji: '🤢', unified: '1f922', name: 'nauseated face' },
    { emoji: '🤮', unified: '1f92e', name: 'face vomiting' },
    { emoji: '🤧', unified: '1f927', name: 'sneezing face' },
    { emoji: '🥵', unified: '1f975', name: 'hot face' },
    { emoji: '🥶', unified: '1f976', name: 'cold face' },
    { emoji: '😵', unified: '1f635', name: 'dizzy face' },
    { emoji: '🤯', unified: '1f92f', name: 'exploding head' },
    { emoji: '🤠', unified: '1f920', name: 'cowboy hat face' },
    { emoji: '🥳', unified: '1f973', name: 'partying face' },
    { emoji: '😎', unified: '1f60e', name: 'smiling face with sunglasses' },
    { emoji: '🤓', unified: '1f913', name: 'nerd face' },
    { emoji: '🧐', unified: '1f9d0', name: 'face with monocle' },
  ],
  emotions: [
    { emoji: '😕', unified: '1f615', name: 'confused face' },
    { emoji: '😟', unified: '1f61f', name: 'worried face' },
    { emoji: '🙁', unified: '1f641', name: 'slightly frowning face' },
    { emoji: '😮', unified: '1f62e', name: 'face with open mouth' },
    { emoji: '😯', unified: '1f62f', name: 'hushed face' },
    { emoji: '😲', unified: '1f632', name: 'astonished face' },
    { emoji: '😳', unified: '1f633', name: 'flushed face' },
    { emoji: '🥺', unified: '1f97a', name: 'pleading face' },
    { emoji: '😦', unified: '1f626', name: 'frowning face with open mouth' },
    { emoji: '😧', unified: '1f627', name: 'anguished face' },
    { emoji: '😨', unified: '1f628', name: 'fearful face' },
    { emoji: '😰', unified: '1f630', name: 'anxious face with sweat' },
    { emoji: '😥', unified: '1f625', name: 'sad but relieved face' },
    { emoji: '😢', unified: '1f622', name: 'crying face' },
    { emoji: '😭', unified: '1f62d', name: 'loudly crying face' },
    { emoji: '😱', unified: '1f631', name: 'face screaming in fear' },
    { emoji: '😖', unified: '1f616', name: 'confounded face' },
    { emoji: '😣', unified: '1f623', name: 'persevering face' },
    { emoji: '😞', unified: '1f61e', name: 'disappointed face' },
    { emoji: '😓', unified: '1f613', name: 'downcast face with sweat' },
    { emoji: '😩', unified: '1f629', name: 'weary face' },
    { emoji: '😫', unified: '1f62b', name: 'tired face' },
    { emoji: '🥱', unified: '1f971', name: 'yawning face' },
    { emoji: '😤', unified: '1f624', name: 'face with steam from nose' },
    { emoji: '😡', unified: '1f621', name: 'pouting face' },
    { emoji: '😠', unified: '1f620', name: 'angry face' },
    { emoji: '🤬', unified: '1f92c', name: 'face with symbols on mouth' },
    { emoji: '😈', unified: '1f608', name: 'smiling face with horns' },
    { emoji: '👿', unified: '1f47f', name: 'angry face with horns' },
    { emoji: '💀', unified: '1f480', name: 'skull' },
    { emoji: '☠️', unified: '2620-fe0f', name: 'skull and crossbones' },
  ],
  gestures: [
    { emoji: '👋', unified: '1f44b', name: 'waving hand' },
    { emoji: '🤚', unified: '1f91a', name: 'raised back of hand' },
    { emoji: '🖐️', unified: '1f590-fe0f', name: 'hand with fingers splayed' },
    { emoji: '✋', unified: '270b', name: 'raised hand' },
    { emoji: '🖖', unified: '1f596', name: 'vulcan salute' },
    { emoji: '👌', unified: '1f44c', name: 'OK hand' },
    { emoji: '🤏', unified: '1f90f', name: 'pinching hand' },
    { emoji: '✌️', unified: '270c-fe0f', name: 'victory hand' },
    { emoji: '🤞', unified: '1f91e', name: 'crossed fingers' },
    { emoji: '🤟', unified: '1f91f', name: 'love-you gesture' },
    { emoji: '🤘', unified: '1f918', name: 'sign of the horns' },
    { emoji: '🤙', unified: '1f919', name: 'call me hand' },
    { emoji: '👈', unified: '1f448', name: 'backhand index pointing left' },
    { emoji: '👉', unified: '1f449', name: 'backhand index pointing right' },
    { emoji: '👆', unified: '1f446', name: 'backhand index pointing up' },
    { emoji: '🖕', unified: '1f595', name: 'middle finger' },
    { emoji: '👇', unified: '1f447', name: 'backhand index pointing down' },
    { emoji: '☝️', unified: '261d-fe0f', name: 'index pointing up' },
    { emoji: '👍', unified: '1f44d', name: 'thumbs up' },
    { emoji: '👎', unified: '1f44e', name: 'thumbs down' },
    { emoji: '✊', unified: '270a', name: 'raised fist' },
    { emoji: '👊', unified: '1f44a', name: 'oncoming fist' },
    { emoji: '🤛', unified: '1f91b', name: 'left-facing fist' },
    { emoji: '🤜', unified: '1f91c', name: 'right-facing fist' },
    { emoji: '👏', unified: '1f44f', name: 'clapping hands' },
    { emoji: '🙌', unified: '1f64c', name: 'raising hands' },
    { emoji: '👐', unified: '1f450', name: 'open hands' },
    { emoji: '🤲', unified: '1f932', name: 'palms up together' },
    { emoji: '🤝', unified: '1f91d', name: 'handshake' },
    { emoji: '🙏', unified: '1f64f', name: 'folded hands' },
  ],
  hearts: [
    { emoji: '❤️', unified: '2764-fe0f', name: 'red heart' },
    { emoji: '🧡', unified: '1f9e1', name: 'orange heart' },
    { emoji: '💛', unified: '1f49b', name: 'yellow heart' },
    { emoji: '💚', unified: '1f49a', name: 'green heart' },
    { emoji: '💙', unified: '1f499', name: 'blue heart' },
    { emoji: '💜', unified: '1f49c', name: 'purple heart' },
    { emoji: '🖤', unified: '1f5a4', name: 'black heart' },
    { emoji: '🤍', unified: '1f90d', name: 'white heart' },
    { emoji: '🤎', unified: '1f90e', name: 'brown heart' },
    { emoji: '💔', unified: '1f494', name: 'broken heart' },
    { emoji: '❣️', unified: '2763-fe0f', name: 'heart exclamation' },
    { emoji: '💕', unified: '1f495', name: 'two hearts' },
    { emoji: '💞', unified: '1f49e', name: 'revolving hearts' },
    { emoji: '💓', unified: '1f493', name: 'beating heart' },
    { emoji: '💗', unified: '1f497', name: 'growing heart' },
    { emoji: '💖', unified: '1f496', name: 'sparkling heart' },
    { emoji: '💘', unified: '1f498', name: 'heart with arrow' },
    { emoji: '💝', unified: '1f49d', name: 'heart with ribbon' },
    { emoji: '💟', unified: '1f49f', name: 'heart decoration' },
  ],
  symbols: [
    { emoji: '💯', unified: '1f4af', name: 'hundred points' },
    { emoji: '💢', unified: '1f4a2', name: 'anger symbol' },
    { emoji: '💥', unified: '1f4a5', name: 'collision' },
    { emoji: '💫', unified: '1f4ab', name: 'dizzy' },
    { emoji: '💦', unified: '1f4a6', name: 'sweat droplets' },
    { emoji: '💨', unified: '1f4a8', name: 'dashing away' },
    { emoji: '🕳️', unified: '1f573-fe0f', name: 'hole' },
    { emoji: '💬', unified: '1f4ac', name: 'speech balloon' },
    { emoji: '👁️‍🗨️', unified: '1f441-fe0f-200d-1f5e8-fe0f', name: 'eye in speech bubble' },
    { emoji: '🗨️', unified: '1f5e8-fe0f', name: 'left speech bubble' },
    { emoji: '🗯️', unified: '1f5ef-fe0f', name: 'right anger bubble' },
    { emoji: '💭', unified: '1f4ad', name: 'thought balloon' },
    { emoji: '💤', unified: '1f4a4', name: 'zzz' },
    { emoji: '🔥', unified: '1f525', name: 'fire' },
    { emoji: '✨', unified: '2728', name: 'sparkles' },
    { emoji: '⭐', unified: '2b50', name: 'star' },
    { emoji: '🌟', unified: '1f31f', name: 'glowing star' },
    { emoji: '🎉', unified: '1f389', name: 'party popper' },
    { emoji: '🎊', unified: '1f38a', name: 'confetti ball' },
  ],
};

export const FREQUENTLY_USED_EMOJIS: Emoji[] = [
  { emoji: '❤️', unified: '2764-fe0f', name: 'red heart' },
  { emoji: '😂', unified: '1f602', name: 'face with tears of joy' },
  { emoji: '😍', unified: '1f60d', name: 'smiling face with heart-eyes' },
  { emoji: '👍', unified: '1f44d', name: 'thumbs up' },
  { emoji: '😊', unified: '1f60a', name: 'smiling face with smiling eyes' },
  { emoji: '🔥', unified: '1f525', name: 'fire' },
  { emoji: '😢', unified: '1f622', name: 'crying face' },
  { emoji: '🎉', unified: '1f389', name: 'party popper' },
  { emoji: '😮', unified: '1f62e', name: 'face with open mouth' },
  { emoji: '😡', unified: '1f621', name: 'pouting face' },
  { emoji: '🙏', unified: '1f64f', name: 'folded hands' },
  { emoji: '💯', unified: '1f4af', name: 'hundred points' },
];

export const ALL_EMOJIS = [
  ...EMOJI_CATEGORIES.smileys,
  ...EMOJI_CATEGORIES.emotions,
  ...EMOJI_CATEGORIES.gestures,
  ...EMOJI_CATEGORIES.hearts,
  ...EMOJI_CATEGORIES.symbols,
];

export function getEmojiByUnified(unified: string): Emoji | undefined {
  return ALL_EMOJIS.find(e => e.unified === unified);
}

export function getUnifiedId(emoji: string): string {
  const found = ALL_EMOJIS.find(e => e.emoji === emoji);
  return found?.unified || emoji;
}
